### ISSUE TITLE
model fails when there is no management placed

### ISSUE THREAD

**Issue by dagaydos21** [ncsu-landscape-dynamics/pops_model_api#1]
If you try to run the model without any management, it fails and gives the error "PoPS Model API not found (404 error)". I tried this no management test in the first year, second year and third year of the simulation and got the same error no matter what year you don't place management.

**Comment by ChrisJones687** [comment]
@dagaydos21 I have deployed the fix for this and tested it to make sure it works but have only ran it once. If it works for well for you let me know and I will close the issue. You should be able to test this side by side with #2 if you eradicate in the first year and then do nothing going forward.

**Comment by dagaydos21** [comment]
I tested this a couple of times, and it looks like it's working well. Thanks!
